name: 'Hello World'

on:

  push:
    branches: none # [main]
  pull_request:
    branches: none # [main]
  workflow_dispatch:
jobs:
  build container:
    runs-on: "ubuntu-latest" 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the Docker image
        working-directory: Meir-Dir
        run: docker build . --file Dockerfile --tag my-hello-world:$(date +%s) 