name: publish
on: 
  push:
    branches: none # [main]
  pull_request:
    branches: none # [main]
  workflow_dispatch:
jobs:
 publish-hello-docker-image:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
     registry: ghcr.io
     username: ${{ github.actor }}
     password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build the hello-docker Docker image
    run: |
       docker build . --tag ghcr.io/meirmany/git-action-flow-hello:latest
       docker run ghcr.io/meirmany/git-action-flow-hello:latest
       docker push ghcr.io/meirmany/git-action-flow-hello:latest